// exam-base/src/containers/account/Profile.tsx
import React, { useContext, useState } from "react";
import { AppContext } from "../../context/AppState";
import { BaseService } from "../../services/base-service";
import { IJwt } from "../../types/IJwt";
import { IMessages } from "../../types/IMessages";

interface FormValues {
    firstname: string;
    lastname: string;
    email: string;
    password: string;
    newPassword: string;
    confirmPassword: string;
}

const Profile = () => {
    const appState = useContext(AppContext);

    const [errors, setErrors] = useState<string[] | undefined>();

    const [form, setForm] = useState<FormValues>({
        firstname: appState.firstName,
        lastname: appState.lastName,
        email: "",
        password: "",
        newPassword: "",
        confirmPassword: "",
    });

    const handleForm = (e: any) => {
        setErrors([]);
        setForm({ ...form, [e.target.name]: e.target.value });
    };

    const handleSubmit = async () => {
        var result = await BaseService.post<IJwt | IMessages>(
            "/account/updateuser",
            {
                firstname: form.firstname,
                lastname: form.lastname,
                email: form.email,
                currentPassword: form.password,
                password:
                    form.newPassword.length !== 0
                        ? form.newPassword
                        : form.password,
            },
            appState.jwt ?? ""
        );

        if (result.ok && result.data) {
            let data = result.data as IJwt;
            appState.setAuthInfo(data.token, data.firstname, data.lastname);
            setErrors(["Successfully updated!"]);
        } else {
            setErrors(result.messages);
        }
    };

    return (
        <>
            <div className="row justify-content-center">
                <h1>Edit Profile</h1>
            </div>
            <div className="container">
                <div className="row">
                    <div className="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <div className="form-group">
                            <label htmlFor="firstname">
                                <b>First name</b>
                            </label>
                            <input
                                type="text"
                                className="form-control"
                                name="firstname"
                                aria-describedby="firstnamehelp"
                                value={form.firstname}
                                onChange={(e) => handleForm(e)}
                                placeholder="Enter First name"
                            />
                            <small
                                id="firstnamehelp"
                                className="form-text text-muted"></small>
                        </div>
                        <div className="form-group">
                            <label htmlFor="lastname">
                                <b>Last name</b>
                            </label>
                            <input
                                type="text"
                                className="form-control"
                                name="lastname"
                                value={form.lastname}
                                onChange={(e) => handleForm(e)}
                                aria-describedby="lastnamehelp"
                                placeholder="Enter Last name"
                            />
                            <small
                                id="lastnamehelp"
                                className="form-text text-muted"></small>
                        </div>
                        <div className="form-group">
                            <label htmlFor="email">
                                <b>E-mail</b>
                            </label>
                            <input
                                type="text"
                                className="form-control"
                                name="email"
                                value={form.email}
                                onChange={(e) => handleForm(e)}
                                aria-describedby="emailHelp"
                                placeholder="Enter new E-mail address"
                            />
                            <small
                                id="emailHelp"
                                className="form-text text-muted"></small>
                        </div>
                        <button
                            onClick={() => handleSubmit()}
                            className="btn btn-primary">
                            Confirm
                        </button>
                    </div>
                    <div className="col-lg-4 col-md-4"></div>
                    <div className="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <div className="form-group">
                            <label htmlFor="password">
                                <b>Current Password</b>
                            </label>
                            <input
                                type="password"
                                className="form-control"
                                name="password"
                                value={form.password}
                                onChange={(e) => handleForm(e)}
                                aria-describedby="passwordhelp"
                                placeholder="Enter current password"
                            />
                            <small
                                id="passwordhelp"
                                className="form-text text-muted"></small>
                        </div>
                        <div className="form-group">
                            <label htmlFor="lastname">
                                <b>New password</b>
                            </label>
                            <input
                                type="password"
                                className="form-control"
                                name="newPassword"
                                value={form.newPassword}
                                onChange={(e) => handleForm(e)}
                                aria-describedby="newPasswordHelp"
                                placeholder="Enter new password"
                            />
                            <small
                                id="newPasswordHelp"
                                className="form-text text-muted"></small>
                        </div>
                        <div className="form-group">
                            <label htmlFor="repeatNewPassword">
                                <b>Repeat new password</b>
                            </label>
                            <input
                                type="password"
                                className="form-control"
                                name="confirmPassword"
                                value={form.confirmPassword}
                                onChange={(e) => handleForm(e)}
                                aria-describedby="repeatnewPasswordHelp"
                                placeholder="Repeat new password"
                            />
                            <small
                                id="repeatnewPasswordHelp"
                                className="form-text text-muted"></small>
                        </div>
                    </div>
                </div>
                <div className="row justify-content-center mt-5">
                    <ul className="list-group">
                        {errors?.map((item, index) => {
                            return (
                                <li
                                    className="list-group-item list-group-item-danger"
                                    key={index}>
                                    {item}
                                </li>
                            );
                        })}
                    </ul>
                </div>
            </div>
        </>
    );
};

export default Profile;

// tanklad-vue/src/views/identity/Profile.vue
<template>
    <div class="row justify-content-center">
        <h1>Edit Profile</h1>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label for="firstname"><b>First name</b></label>
                    <input type="text" v-model="firstName" class="form-control" id="firstname" aria-describedby="firstnamehelp" placeholder="Enter First name">
                    <small id="firstnamehelp" class="form-text text-muted"></small>
                </div>
                <div class="form-group">
                    <label for="lastname"><b>Last name</b></label>
                    <input type="text" v-model="lastName" class="form-control" id="lastname" aria-describedby="lastnamehelp" placeholder="Enter Last name">
                    <small id="lastnamehelp" class="form-text text-muted"></small>
                </div>
                <div class="form-group">
                    <label for="email"><b>E-mail</b></label>
                    <input type="text" v-model="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter new E-mail address">
                    <small id="emailHelp" class="form-text text-muted"></small>
                </div>
                <button class="btn btn-primary" @click="confirm()">Confirm</button>
            </div>
            <div class="col-lg-4 col-md-4"></div>
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label for="password"><b>Current Password</b></label>
                    <input type="password" v-model="pass" class="form-control" id="password" aria-describedby="passwordhelp" placeholder="Enter current password">
                    <small id="passwordhelp" class="form-text text-muted"></small>
                </div>
                <div class="form-group">
                    <label for="lastname"><b>New password</b></label>
                    <input type="password" v-model="newPass" class="form-control" id="newPassword" aria-describedby="newPasswordHelp" placeholder="Enter new password">
                    <small id="newPasswordHelp" class="form-text text-muted"></small>
                </div>
                <div class="form-group">
                    <label for="repeatNewPassword"><b>Repeat new password</b></label>
                    <input type="password" v-model="confirmPass" class="form-control" id="repeatNewPassword" aria-describedby="repeatnewPasswordHelp" placeholder="Repeat new password">
                    <small id="repeatnewPasswordHelp" class="form-text text-muted"></small>
                </div>
                <button class="btn btn-primary" @click="confirm()">Confirm</button>
            </div>
        </div>
        <div class="row justify-content-center mt-5">
            <ul class="list-group">
                <li class="list-group-item list-group-item-danger" v-for="(error, index) in errors" :key="index">
                    {{error}}
                </li>
            </ul>
        </div>
    </div>
</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import store from "@/store/index";
import jwtDecode from 'jwt-decode';
import { error } from "node_modules/@types/jquery";
@Options({
    components: {},
})
export default class Profile extends Vue {
    errors: string[] | null = null;

    firstName: string = "";
    lastName: string = "";
    email: string = "";
    pass: string = "";
    newPass: string = "";
    confirmPass: string = "";

    mounted(): void {
        this.firstName = store.state.firstname;
        this.lastName = store.state.lastname;
        if (store.state.token !== null) {
            var decoded: any = jwtDecode(store.state.token)
            this.email = decoded["http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"];
        }
    }

    valid(): boolean {
        return this.newPass === this.confirmPass;
    }

    async confirm(): Promise<void> {
        if (this.valid()) {
            console.log(this.firstName);
            const errors = await store.dispatch('editProfile', { firstname: this.firstName, lastname: this.lastName, email: this.email, password: this.newPass !== "" ? this.newPass : null, currentPassword: this.pass !== "" ? this.pass : null });
            this.errors = errors;
            if (this.errors === undefined) {
                this.errors = ["Successfully updated!"];
            }
        } else {
            this.errors = ["Passwords do not match!"];
        }
    }
}
</script>
