// tanklad-vue/src/views/identity/Register.vue
<template>
    <h1>Register</h1>
    <div class="row">
        <div class="col-md-4">
            <section>
                <form id="account" method="post">
                    <h4>Create a new account.</h4>
                    <hr />
                    <div
                        class="text-danger validation-summary-valid"
                        data-valmsg-summary="true"
                    >
                        <ul>
                            <li style="display: none"></li>
                        </ul>
                    </div>
                    <div class="form-group">
                        <label for="Input_Firstname">First name</label>
                        <input
                            class="form-control valid"
                            type="text"
                            id="Input_Firstname"
                            name="Input.Firstname"
                            v-model="firstname"
                        />
                    </div>
                    <div class="form-group">
                        <label for="Input_Lastname">Last name</label>
                        <input
                            class="form-control valid"
                            type="text"
                            id="Input_Lastname"
                            name="Input.Lastname"
                            v-model="lastname"
                        />
                    </div>
                    <div class="form-group">
                        <label for="Input_Email">Email</label>
                        <input
                            class="form-control valid"
                            type="email"
                            id="Input_Email"
                            name="Input.Email"
                            v-model="email"
                        />
                    </div>
                    <div class="form-group">
                        <label for="Input_Password">Password</label>
                        <input
                            class="form-control valid"
                            type="password"
                            id="Input_Password"
                            name="Input.Password"
                            v-model="password"
                        />
                    </div>
                    <div class="form-group">
                        <label for="Input_Confirmpassword">Confirm Password</label>
                        <input
                            class="form-control valid"
                            type="password"
                            id="Input_Confirmpassword"
                            name="Input.Confirmpassword"
                            v-model="confirmPassword"
                        />
                    </div>
                    <div class="form-group">
                        <button
                            @click="registerClicked($event)"
                            type="submit"
                            class="btn btn-primary"
                        >
                            Register
                        </button>
                    </div>
                </form>
            </section>
        </div>
        <div class="col-md-4 justify-content-center">
            <ul class="list-group">
                <li class="list-group-item list-group-item-danger" v-for="(message, index) in messages" :key="index">
                    {{message}}
                </li>
            </ul>
        </div>
    </div>
</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import store from "@/store/index";
@Options({
    components: {},
})
export default class Login extends Vue {
    firstname: string = "";
    lastname: string = "";
    email: string = "";
    password: string = "";
    confirmPassword: string = "";
    messages: string[] | null = null;

    valid(): boolean {
        return this.password !== "" && this.password === this.confirmPassword;
    }

    async registerClicked(event: Event): Promise<void> {
        event.preventDefault();
        if (this.valid()) {
            console.log(this.password);
            const result = await store.dispatch("register", { firstname: this.firstname, lastname: this.lastname, email: this.email, password: this.password });
            if (result === true) {
                this.$router.push('/')
            } else {
                this.messages = result;
            }
        } else {
            this.messages = ["Passwords do not match"];
        }
    }
}
</script>

// exam-base/src/containers/account/Register.tsx
import React, { useContext, useState } from "react";
import { AppContext } from "../../context/AppState";
import { BaseService } from "../../services/base-service";
import { IJwt } from "../../types/IJwt";
import { useHistory } from "react-router-dom";

const Register = () => {
    const history = useHistory();
    const appState = useContext(AppContext);

    const [form, setValues] = useState({
        email: "",
        password: "",
        firstname: "",
        lastname: "",
    });
    let errors = null as string[] | null;
    const [errorMessages, setErrors] = useState(errors);
    const [confirmPwd, setConfirmPwd] = useState("");

    const postData = async (e: any) => {
        e.preventDefault();
        if (form.password !== confirmPwd) {
            setErrors(["Passwords do not match"]);
            return;
        }
        let result = await BaseService.post<IJwt>("/account/register", form);
        if (result.ok && result.data) {
            console.log(result.data);
            appState.setAuthInfo(
                result.data.token,
                result.data.firstname,
                result.data.lastname
            );
            history.replace("/");
        } else {
            setErrors(result.messages ?? ["Server is not responding..."]);
            console.log(result.messages);
        }
    };
    return (
        <>
            <h1 className="row justify-content-center mb-5">
                Register a new account
            </h1>
            <div className="row justify-content-center">
                <form className="col-4" onSubmit={(e) => postData(e)}>
                    <div className="form-group">
                        <label htmlFor="exampleInputEmail1">
                            Email address
                        </label>
                        <input
                            type="email"
                            className="form-control"
                            id="exampleInputEmail1"
                            value={form.email}
                            onChange={(e) => {
                                setValues({
                                    ...form,
                                    email: e.target.value,
                                });
                                setErrors(null);
                            }}
                        />
                    </div>
                    <div className="form-group">
                        <label htmlFor="firstName">First name</label>
                        <input
                            type="text"
                            className="form-control"
                            id="firstName"
                            value={form.firstname}
                            onChange={(e) => {
                                setValues({
                                    ...form,
                                    firstname: e.target.value,
                                });
                                setErrors(null);
                            }}
                        />
                    </div>
                    <div className="form-group">
                        <label htmlFor="lastName">Last name</label>
                        <input
                            type="text"
                            className="form-control"
                            id="lastName"
                            value={form.lastname}
                            onChange={(e) => {
                                setValues({
                                    ...form,
                                    lastname: e.target.value,
                                });
                                setErrors(null);
                            }}
                        />
                    </div>
                    <div className="form-group">
                        <label htmlFor="exampleInputPassword1">Password</label>
                        <input
                            type="password"
                            className="form-control"
                            id="exampleInputPassword1"
                            value={form.password}
                            onChange={(e) => {
                                setValues({
                                    ...form,
                                    password: e.target.value,
                                });
                                setErrors(null);
                            }}
                        />
                    </div>
                    <div className="form-group">
                        <label htmlFor="confirmPwd">Confirm Password</label>
                        <input
                            type="password"
                            className="form-control"
                            id="confirmPwd"
                            value={confirmPwd}
                            onChange={(e) => {
                                setConfirmPwd(e.target.value);
                                setErrors(null);
                            }}
                        />
                    </div>
                    <button type="submit" className="btn btn-primary mb-5">
                        Register
                    </button>
                    {errorMessages
                        ? errorMessages.map((msg, index) => (
                              <div
                                  key={index}
                                  className="alert alert-danger"
                                  role="alert">
                                  {msg}
                              </div>
                          ))
                        : null}
                </form>
            </div>
        </>
    );
};

export default Register;
