// tanklad-vue/src/components/GasStation.vue
<template>
    <div class="card h-100 gasstation-card">
        <div class="card-body row">
            <div class="h-85 col-4">
                <img v-if="gasStation.name.includes('Alexela')" class="logo" src="https://seeklogo.com/images/A/alexela-logo-D0EC116C33-seeklogo.com.png"/>
                <img v-if="gasStation.name.includes('Olerex')" class="logo" src="https://ehl.org.ee/wp-content/uploads/2018/10/Olerex-logo.jpg"/>
                <p class="card-text d-none d-sm-block">
                    <small class="text-muted">Last updated today</small>
                </p>
            </div>
            <div class="h-100 col-8">
                <h5 class="row card-title justify-content-center">
                    {{ gasStation.name.toUpperCase() }}
                </h5>
                <div class="row" v-for="(item, index) in gasStation.fuelTypes" :key="index">
                    <p class="row card-text justify-content-end col-6">
                        <b>{{ gasStation.fuelTypes[index].fuelType.name.toUpperCase() }}:</b>
                    </p>
                    <p class="row card-text justify-content-end col-6">
                        <b>{{ gasStation.fuelTypes[index].price }}€</b>
                    </p>
                </div>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import { IGasStation } from "@/domain/IGasStation";
@Options({
    components: {},
    // List all the external properties this component uses.
    props: {
        gasStation: Object,
    },
})
export default class GasStation extends Vue {
    gasStation!: IGasStation;
}
</script>
<style scoped>
.gasstation-card {
    background-color: paleturquoise;
}

.logo {
    width: 100%;
    height: 100%;
    object-fit: contain;
}

.card-title {
    font-size: 1.5em;
    font-weight: bold;
}
</style>

// tanklad-react/src/components/GasStation.tsx
import React from "react";
import { IGasStation } from "../domain/IGasStation";

const GasStation = (gasStation: IGasStation) => {
    return (
        <>
            <div className="card h-100 gasstation-card">
                <div className="card-body row">
                    <div className="h-85 col-5">
                        <img
                            className="logo"
                            src="https://ehl.org.ee/wp-content/uploads/2018/10/Olerex-logo.jpg"
                            alt="Gas station logo"
                        />
                        <p className="card-text d-none d-sm-block">
                            <small className="text-muted">
                                Last updated: {new Date().getDate()}/
                                {new Date().getUTCMonth() + 1}/
                                {new Date().getFullYear()}
                            </small>
                        </p>
                    </div>
                    <div className="h-100 col-7">
                        <h5 className="row card-title justify-content-center">
                            <div className="row col-11 justify-content-center">
                                {gasStation.name}
                            </div>
                            <div className="row col-1">
                                <a
                                    title="Add as favorite"
                                    className="rounded-circle btn btn-primary btn-sm my-auto">
                                    +
                                </a>
                            </div>
                        </h5>
                        {/*Foreach fueltype starts*/}
                        <div className="row">
                            <p className="row card-text justify-content-end col-6">
                                <b>Diisel</b>
                            </p>
                            <p className="row card-text justify-content-end col-6">
                                <b>1.225 EUR</b>
                            </p>
                        </div>
                        {/*Foreach ends*/}
                    </div>
                </div>
            </div>
        </>
    );
};

export default GasStation;
